// GENERATED by scripts/gen-types.mjs from the control plane OpenAPI. Do not edit.
export interface paths {
    "/api/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Costs
         * @description Spend and volume per vendor; `project_id` narrows to that client's runs.
         *
         *     `exclude_source=demo` leaves seeded demonstration rows out of the totals.
         */
        get: operations["costs_api_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Jobs */
        get: operations["all_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        /** Update Project */
        put: operations["update_project_api_projects__project_id__put"];
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/actions/{action_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Action */
        put: operations["update_action_api_projects__project_id__actions__action_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/consolidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consolidate
         * @description Recompute the project's positions now, over its window (or a custom one).
         */
        post: operations["consolidate_api_projects__project_id__consolidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/crawls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crawls */
        get: operations["crawls_api_projects__project_id__crawls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_projects__project_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insights
         * @description Verdicts, what changed, action cards, fan-out, claims, trust, pages.
         */
        get: operations["insights_api_projects__project_id__insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Jobs */
        get: operations["project_jobs_api_projects__project_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Positions */
        get: operations["positions_api_projects__project_id__positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prompts */
        get: operations["list_prompts_api_projects__project_id__prompts_get"];
        put?: never;
        /** Add Prompt */
        post: operations["add_prompt_api_projects__project_id__prompts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/prompts/{tracked_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Prompt */
        put: operations["update_prompt_api_projects__project_id__prompts__tracked_id__put"];
        post?: never;
        /** Delete Prompt */
        delete: operations["delete_prompt_api_projects__project_id__prompts__tracked_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/prompts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Prompts */
        post: operations["import_prompts_api_projects__project_id__prompts_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results */
        get: operations["results_api_projects__project_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run */
        post: operations["run_api_projects__project_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_projects__project_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Samples
         * @description Raw answer samples with full text, the engine's queries, claims and snippets.
         */
        get: operations["samples_api_projects__project_id__samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionCard
         * @description A prescribed action with its evidence and analyst state.
         */
        ActionCard: {
            engine?: components["schemas"]["Engine"] | null;
            evidence: components["schemas"]["ActionEvidence"];
            /** Id */
            id: string;
            /** Impact Score */
            impact_score: number;
            /**
             * Metric
             * @description Number scored after the next consolidation.
             * @default cited_rate
             */
            metric: string;
            /** Note */
            note?: string | null;
            /**
             * Outcome
             * @description pending | improved | unchanged | regressed
             * @default pending
             */
            outcome: string;
            /** Owner */
            owner?: string | null;
            /** Prescription */
            prescription: string;
            /** Prompt Ids */
            prompt_ids?: string[];
            /**
             * Status
             * @default open
             */
            status: string;
            /** Subtopic */
            subtopic: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * ActionEvidence
         * @description Everything an analyst needs to trust a card.
         */
        ActionEvidence: {
            /** Domains */
            domains?: components["schemas"]["DomainShare"][];
            /** Numbers */
            numbers?: {
                [key: string]: number;
            };
            /** Queries */
            queries?: string[];
            /** Quotes */
            quotes?: components["schemas"]["EvidenceQuote"][];
            /** Urls */
            urls?: string[];
        };
        /**
         * ActionUpdate
         * @description Body for `PUT /api/projects/{id}/actions/{action_id}`.
         */
        ActionUpdate: {
            /** Note */
            note?: string | null;
            /** Owner */
            owner?: string | null;
            /** Status */
            status?: string | null;
        };
        /**
         * AnswerSample
         * @description One raw engine answer, kept so model shifts can be told apart from content changes.
         */
        AnswerSample: {
            /**
             * Answer Excerpt
             * @default
             */
            answer_excerpt: string;
            /**
             * Answer Text
             * @description Full answer text (cycle 0011).
             * @default
             */
            answer_text: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Citation Claims */
            citation_claims?: components["schemas"]["CitationClaim"][];
            /** Citation Links */
            citation_links?: components["schemas"]["Citation"][];
            /** Cited Domains */
            cited_domains?: string[];
            /** Client Cited */
            client_cited: boolean;
            /** Client Rank */
            client_rank?: number | null;
            /** Consulted Urls */
            consulted_urls?: string[];
            engine: components["schemas"]["Engine"];
            /**
             * Mention Detected
             * @default false
             */
            mention_detected: boolean;
            /** Mentions */
            mentions?: components["schemas"]["MentionSnippet"][];
            /** Model */
            model: string;
            /** Prompt Id */
            prompt_id: string;
            /** Response Id */
            response_id?: string | null;
            /**
             * Search Queries
             * @description The engine's own sub-queries (query fan-out).
             */
            search_queries?: string[];
            /** Source Snippets */
            source_snippets?: components["schemas"]["SourceSnippet"][];
            /** Web Triggered */
            web_triggered: boolean;
        };
        /**
         * Citation
         * @description One source an engine attributed its answer to.
         */
        Citation: {
            /**
             * Domain
             * @description Registrable domain, e.g. `gep.com`.
             */
            domain: string;
            /**
             * Position
             * @description 1-indexed order of first appearance.
             */
            position: number;
            /**
             * Resolved
             * @description False when `url` is still a vendor redirect whose real destination could not be resolved (see Gemini connector).
             * @default true
             */
            resolved: boolean;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /**
         * CitationClaim
         * @description A sentence of the answer and the source the engine attributed it to.
         */
        CitationClaim: {
            /**
             * End
             * @default 0
             */
            end: number;
            /** Sentence */
            sentence: string;
            /**
             * Start
             * @description Character span in the answer text.
             * @default 0
             */
            start: number;
            /** Url */
            url: string;
        };
        /**
         * CitationSnapshot
         * @description Aggregated citation outcome for one prompt on one engine at one time.
         */
        CitationSnapshot: {
            /**
             * Answer Excerpt
             * @default
             */
            answer_excerpt: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at?: string;
            /**
             * Citation Links
             * @description Every URL cited across samples, best position first, de-duplicated.
             */
            citation_links?: components["schemas"]["Citation"][];
            /**
             * Cited Domains
             * @description Union across samples, most frequent first.
             */
            cited_domains?: string[];
            /** Client Best Rank */
            client_best_rank?: number | null;
            /** Client Citation Rate */
            client_citation_rate: number;
            /**
             * Client Cited
             * @description Cited in at least half of the successful samples.
             */
            client_cited: boolean;
            /** Client Cited Samples */
            client_cited_samples: number;
            /** Client Mean Rank */
            client_mean_rank?: number | null;
            /**
             * Client Urls
             * @description The client's own URLs among the citations.
             */
            client_urls?: string[];
            /**
             * Competitor Citations
             * @description Best (lowest) rank per competitor domain.
             */
            competitor_citations?: {
                [key: string]: number;
            };
            /**
             * Competitor Mentions
             * @description Samples in which each competitor was named.
             */
            competitor_mentions?: {
                [key: string]: number;
            };
            /**
             * Consulted Urls
             * @description URLs the engine read but did not cite inline.
             */
            consulted_urls?: string[];
            engine: components["schemas"]["Engine"];
            /**
             * Failed Samples
             * @default 0
             */
            failed_samples: number;
            /**
             * Mention Detected
             * @description Client named in the answer text of at least one sample.
             * @default false
             */
            mention_detected: boolean;
            /**
             * Mention Rate
             * @default 0
             */
            mention_rate: number;
            /**
             * Mention Snippets
             * @description Distinct client-mention sentences, at most ten.
             */
            mention_snippets?: components["schemas"]["MentionSnippet"][];
            /** Model */
            model: string;
            /**
             * Response Ids
             * @description Vendor response ids of the samples, for audits.
             */
            response_ids?: string[];
            /**
             * Reused
             * @description True when copied from a recent run instead of re-sampled.
             * @default false
             */
            reused: boolean;
            /** Samples */
            samples: number;
            /** Web Trigger Rate */
            web_trigger_rate: number;
        };
        /**
         * ClaimEntry
         * @description A sentence attributed by an engine to a source.
         */
        ClaimEntry: {
            /** Domain */
            domain: string;
            engine: components["schemas"]["Engine"];
            /** Is Client */
            is_client: boolean;
            /** Is Competitor */
            is_competitor: boolean;
            /** Prompt Id */
            prompt_id: string;
            /** Sentence */
            sentence: string;
            /** Url */
            url: string;
        };
        /**
         * ClientProfile
         * @description Everything the tracker needs to know about one client LOB.
         */
        ClientProfile: {
            /**
             * Aliases
             * @description Other names the brand appears under (GEP SMART, NEXXE).
             */
            aliases?: string[];
            /** Brand Name */
            brand_name: string;
            /** Competitor Domains */
            competitor_domains?: string[];
            /**
             * Competitor Names
             * @description Competitor brand names for mention detection (SAP Ariba, Coupa). When empty, the first label of each competitor domain is used.
             */
            competitor_names?: string[];
            /**
             * Domains
             * @description Client domains, bare hosts or URLs.
             */
            domains: string[];
            /**
             * Landing Pages
             * @description Client URLs available for mapping.
             */
            landing_pages?: string[];
            /**
             * Lob
             * @description Line of business, e.g. 'Procurement Software'.
             */
            lob: string;
            /** Seed Keywords */
            seed_keywords: string[];
            /**
             * Subtopics
             * @description Optional analyst-defined subtopics. Seed keywords are used when empty.
             */
            subtopics?: string[];
        };
        /**
         * ConsolidatedPosition
         * @description One prompt on one platform, positioned over a window of crawls.
         */
        ConsolidatedPosition: {
            /** Best Rank */
            best_rank?: number | null;
            /** Citation Rate */
            citation_rate: number;
            /** Cited */
            cited: boolean;
            /** Cited Domain Share */
            cited_domain_share?: {
                [key: string]: number;
            };
            /** Cited Samples */
            cited_samples: number;
            /** Competitor Citations */
            competitor_citations?: {
                [key: string]: number;
            };
            engine: components["schemas"]["Engine"];
            /** Failed Samples */
            failed_samples: number;
            /**
             * First Run At
             * Format: date-time
             */
            first_run_at: string;
            /**
             * Last Run At
             * Format: date-time
             */
            last_run_at: string;
            /** Mean Rank */
            mean_rank?: number | null;
            /** Mention Rate */
            mention_rate: number;
            /** Mention Samples */
            mention_samples: number;
            /** Mentioned */
            mentioned: boolean;
            /** Organic Keyword Best */
            organic_keyword_best?: number | null;
            /** Organic Keyword Mean */
            organic_keyword_mean?: number | null;
            /** Organic Prompt Best */
            organic_prompt_best?: number | null;
            /** Organic Prompt Mean */
            organic_prompt_mean?: number | null;
            /** Prompt Id */
            prompt_id: string;
            /** Rank Distribution */
            rank_distribution?: {
                [key: string]: number;
            };
            /**
             * Runs
             * @description Pipeline runs that contributed.
             */
            runs: number;
            /** Samples */
            samples: number;
        };
        /**
         * ConsolidateRequest
         * @description Body for `POST /api/projects/{id}/consolidate`.
         */
        ConsolidateRequest: {
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Window Runs
             * @description Override the project's consolidation window.
             */
            window_runs?: number | null;
        };
        /**
         * Consolidation
         * @description A dated position set for a project.
         */
        Consolidation: {
            /**
             * Consolidated At
             * Format: date-time
             */
            consolidated_at: string;
            /** First Run At */
            first_run_at?: string | null;
            /** Id */
            id: string;
            /** Last Run At */
            last_run_at?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Positions Count
             * @default 0
             */
            positions_count: number;
            /** Project Id */
            project_id: string;
            /** Project Run Ids */
            project_run_ids?: string[];
            /** Prompts */
            prompts: number;
            /** Run Ids */
            run_ids?: string[];
            /**
             * Trigger
             * @description auto | manual
             */
            trigger: string;
            /** Window Runs */
            window_runs: number;
        };
        /**
         * CostRecommendation
         * @description A proposed value for one `COST_*` setting.
         */
        CostRecommendation: {
            /**
             * Basis
             * @description vendor-reported | modelled | estimate-only
             */
            basis: string;
            /** Basis Calls */
            basis_calls: number;
            /** Current */
            current: number;
            /** Observed Mean */
            observed_mean: number;
            /** Setting */
            setting: string;
            /** Suggested */
            suggested: number;
            /** Unit */
            unit: string;
            /** Vendor */
            vendor: string;
        };
        /**
         * CostReport
         * @description Everything the CLI, API and UI show about spend.
         */
        CostReport: {
            /** By Source */
            by_source?: {
                [key: string]: number;
            };
            /** Calls */
            calls: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Notes */
            notes?: string[];
            /** Recommendations */
            recommendations?: components["schemas"]["CostRecommendation"][];
            /** Runs */
            runs?: components["schemas"]["RunCost"][];
            /** Since */
            since?: string | null;
            /** Total Actual Usd */
            total_actual_usd: number;
            /** Total Estimated Usd */
            total_estimated_usd: number;
            /** Vendors */
            vendors?: components["schemas"]["VendorCost"][];
        };
        /**
         * DomainShare
         * @description Share of answers citing a domain.
         */
        DomainShare: {
            /** Domain */
            domain: string;
            /** Share */
            share: number;
        };
        /**
         * Engine
         * @description AI answer engines the tracker audits.
         *
         *     Values name what was *actually called*, not the consumer product it
         *     approximates — `CHATGPT_SEARCH` is the OpenAI Responses API with the
         *     `web_search` tool, which is the closest programmatic proxy for ChatGPT
         *     Search, not ChatGPT itself.
         * @enum {string}
         */
        Engine: "GOOGLE_AI_OVERVIEW" | "CHATGPT_SEARCH" | "PERPLEXITY" | "GEMINI";
        /**
         * EngineHealth
         * @description One platform's verdict for the project.
         */
        EngineHealth: {
            /** Best Rank */
            best_rank?: number | null;
            /** Cited Rate */
            cited_rate: number;
            /** Crawls */
            crawls: number;
            /** Delta Cited Rate */
            delta_cited_rate?: number | null;
            engine: components["schemas"]["Engine"];
            /** Losing To */
            losing_to?: string | null;
            /** Mention Rate */
            mention_rate: number;
            /** Prompts */
            prompts: number;
            /** Samples */
            samples: number;
            /**
             * Verdict
             * @description winning | present | invisible | losing
             */
            verdict: string;
            /**
             * Volatility
             * @description 0 stable, 1 coin-flip across samples.
             */
            volatility: number;
        };
        /**
         * EvidenceQuote
         * @description A sentence from an engine answer, with provenance.
         */
        EvidenceQuote: {
            /** Captured At */
            captured_at?: string | null;
            engine: components["schemas"]["Engine"];
            /** Entity */
            entity?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Text */
            text: string;
        };
        /**
         * FanoutQuery
         * @description A sub-query an engine ran to answer the project's prompts.
         */
        FanoutQuery: {
            /**
             * Client Covered
             * @description A client page was cited in an answer that ran this query.
             */
            client_covered: boolean;
            /** Engines */
            engines: components["schemas"]["Engine"][];
            /** Prompts */
            prompts: number;
            /** Query */
            query: string;
            /** Subtopic */
            subtopic: string;
        };
        /**
         * FreshnessProfile
         * @description Age of cited sources on one platform (vendor-dated sources only).
         */
        FreshnessProfile: {
            /** Client Median Age Days */
            client_median_age_days?: number | null;
            /** Competitor Median Age Days */
            competitor_median_age_days?: number | null;
            /** Dated Sources */
            dated_sources: number;
            engine: components["schemas"]["Engine"];
            /** Median Age Days */
            median_age_days?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportBody
         * @description Prompts-file text posted from the browser (files are read client-side).
         */
        ImportBody: {
            /** Text */
            text: string;
        };
        /**
         * InsightBasis
         * @description What the insights were computed from.
         */
        InsightBasis: {
            /**
             * Computed From
             * @description consolidation | latest_crawl | none
             */
            computed_from: string;
            /** Consolidation Id */
            consolidation_id: string | null;
            /** Crawls */
            crawls: number;
            /** Low Confidence */
            low_confidence: boolean;
            /** Samples */
            samples: number;
        };
        /**
         * InsightChange
         * @description One movement between the last two position sets.
         */
        InsightChange: {
            /** After */
            after: string;
            /** Before */
            before: string;
            engine: components["schemas"]["Engine"];
            /** Kind */
            kind: string;
            /** Prompt Id */
            prompt_id: string;
            /** Prompt Text */
            prompt_text: string;
            /** Text */
            text: string;
        };
        /**
         * InsightsView
         * @description Everything the Overview, Actions and Atlas pages show.
         */
        InsightsView: {
            /** Actions */
            actions?: components["schemas"]["ActionCard"][];
            basis: components["schemas"]["InsightBasis"];
            /** Changes */
            changes?: components["schemas"]["InsightChange"][];
            /** Claims */
            claims?: components["schemas"]["ClaimEntry"][];
            /** Client Pages */
            client_pages?: components["schemas"]["PageInventory"][];
            /** Fanout */
            fanout?: components["schemas"]["FanoutQuery"][];
            /** Freshness */
            freshness?: components["schemas"]["FreshnessProfile"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Health */
            health?: components["schemas"]["EngineHealth"][];
            /** Placement */
            placement?: components["schemas"]["PlacementProfile"][];
            /** Read But Rejected */
            read_but_rejected?: components["schemas"]["RejectedPage"][];
            /** Trust Profile */
            trust_profile?: components["schemas"]["TrustShare"][];
            /** Winning Pages */
            winning_pages?: components["schemas"]["PageInventory"][];
        };
        /**
         * JobState
         * @description Lifecycle of a queued run.
         * @enum {string}
         */
        JobState: "queued" | "running" | "finished" | "failed";
        /**
         * MentionSnippet
         * @description One sentence of an answer that names the client or a competitor.
         */
        MentionSnippet: {
            /**
             * Entity
             * @description 'client' or the competitor label the term belongs to.
             */
            entity: string;
            /** Snippet */
            snippet: string;
            /**
             * Term
             * @description The brand term that matched.
             */
            term: string;
        };
        /**
         * OrganicRankSnapshot
         * @description Client and competitor positions in Google's classic organic results.
         */
        OrganicRankSnapshot: {
            /**
             * Captured At
             * Format: date-time
             */
            captured_at?: string;
            /**
             * Client Position
             * @description Best across samples.
             */
            client_position?: number | null;
            /** Client Url */
            client_url?: string | null;
            /**
             * Competitor Positions
             * @description Best position per competitor domain.
             */
            competitor_positions?: {
                [key: string]: number;
            };
            /**
             * Device
             * @default desktop
             */
            device: string;
            /**
             * Organic Results
             * @description Top-10 results with title and snippet (cycle 0011).
             */
            organic_results?: components["schemas"]["OrganicResult"][];
            /** Paa Questions */
            paa_questions?: string[];
            /** Query */
            query: string;
            query_kind: components["schemas"]["RankQueryKind"];
            /** Related Searches */
            related_searches?: string[];
            /** Samples */
            samples: number;
            /**
             * Top Domains
             * @description Top-10 registrable domains, rank order.
             */
            top_domains?: string[];
        };
        /**
         * OrganicResult
         * @description One classic (blue-link) Google organic result.
         */
        OrganicResult: {
            /**
             * Domain
             * @description Registrable domain.
             */
            domain: string;
            /**
             * Position
             * @description 1-indexed rank as Google rendered it.
             */
            position: number;
            /** Snippet */
            snippet?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /**
         * PageInventory
         * @description A cited page and how often it wins.
         */
        PageInventory: {
            /** Citations */
            citations: number;
            /** Date */
            date?: string | null;
            /** Domain */
            domain: string;
            /** Engines */
            engines: components["schemas"]["Engine"][];
            /** Is Client */
            is_client: boolean;
            /** Prompts */
            prompts: number;
            /** Snippet */
            snippet?: string | null;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /**
         * PlacementProfile
         * @description Where the brand appears inside answers on one platform.
         */
        PlacementProfile: {
            engine: components["schemas"]["Engine"];
            /** First Third */
            first_third: number;
            /** In List */
            in_list: number;
            /** In Table */
            in_table: number;
            /** Recommendation Sentence */
            recommendation_sentence: number;
            /** Samples With Mention */
            samples_with_mention: number;
        };
        /**
         * PositionsView
         * @description What the Results tab shows in consolidated mode.
         */
        PositionsView: {
            consolidation?: components["schemas"]["Consolidation"] | null;
            /** History */
            history?: components["schemas"]["Consolidation"][];
            /** Positions */
            positions?: components["schemas"]["ConsolidatedPosition"][];
            /**
             * Runs Since Last
             * @default 0
             */
            runs_since_last: number;
        };
        /**
         * Project
         * @description A stored project.
         */
        Project: {
            client: components["schemas"]["ClientProfile"];
            /**
             * Consolidation Runs
             * @description Consolidate positions after every N full crawls of the project. Independent of the run interval: with a 2-day interval and 3, positions are consolidated every 6 days from all three crawls.
             * @default 3
             */
            consolidation_runs: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Engine Models
             * @description Model selection per platform (e.g. CHATGPT_SEARCH -> gpt-4o).
             */
            engine_models?: {
                [key: string]: string;
            };
            /** Engines */
            engines?: components["schemas"]["Engine"][];
            /**
             * Generate Prompts
             * @description Also run the Semrush-generated 10+10 set at the interval.
             * @default false
             */
            generate_prompts: boolean;
            /** Id */
            id: string;
            /**
             * Interval
             * @description Default run interval for prompts.
             * @default daily
             */
            interval: string;
            /** Max Engine Calls */
            max_engine_calls?: number | null;
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Resolve Redirects
             * @default false
             */
            resolve_redirects: boolean;
            /** Reuse Within Hours */
            reuse_within_hours?: number | null;
            /** Samples Per Engine */
            samples_per_engine?: number | null;
            /**
             * Track Keyword Rank
             * @default true
             */
            track_keyword_rank: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectCreate
         * @description Body for creating a project.
         */
        ProjectCreate: {
            client: components["schemas"]["ClientProfile"];
            /**
             * Consolidation Runs
             * @description Consolidate positions after every N full crawls of the project. Independent of the run interval: with a 2-day interval and 3, positions are consolidated every 6 days from all three crawls.
             * @default 3
             */
            consolidation_runs: number;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Engine Models
             * @description Model selection per platform (e.g. CHATGPT_SEARCH -> gpt-4o).
             */
            engine_models?: {
                [key: string]: string;
            };
            /** Engines */
            engines?: components["schemas"]["Engine"][];
            /**
             * Generate Prompts
             * @description Also run the Semrush-generated 10+10 set at the interval.
             * @default false
             */
            generate_prompts: boolean;
            /**
             * Interval
             * @description Default run interval for prompts.
             * @default daily
             */
            interval: string;
            /** Max Engine Calls */
            max_engine_calls?: number | null;
            /** Name */
            name: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Resolve Redirects
             * @default false
             */
            resolve_redirects: boolean;
            /** Reuse Within Hours */
            reuse_within_hours?: number | null;
            /** Samples Per Engine */
            samples_per_engine?: number | null;
            /**
             * Track Keyword Rank
             * @default true
             */
            track_keyword_rank: boolean;
        };
        /**
         * ProjectRunRecord
         * @description One crawl of a project: a job that produced at least one pipeline run.
         */
        ProjectRunRecord: {
            /** Batches */
            batches: number;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /**
             * Full
             * @description True unless the run was restricted to selected prompts.
             */
            full: boolean;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Prompts Run */
            prompts_run: number;
            /** Run Ids */
            run_ids?: string[];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Statuses */
            statuses?: string[];
        };
        /**
         * ProjectUpdate
         * @description Partial update; only supplied fields change.
         */
        ProjectUpdate: {
            client?: components["schemas"]["ClientProfile"] | null;
            /** Consolidation Runs */
            consolidation_runs?: number | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Engine Models */
            engine_models?: {
                [key: string]: string;
            } | null;
            /** Engines */
            engines?: components["schemas"]["Engine"][] | null;
            /** Generate Prompts */
            generate_prompts?: boolean | null;
            /** Interval */
            interval?: string | null;
            /** Max Engine Calls */
            max_engine_calls?: number | null;
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            /** Resolve Redirects */
            resolve_redirects?: boolean | null;
            /** Reuse Within Hours */
            reuse_within_hours?: number | null;
            /** Samples Per Engine */
            samples_per_engine?: number | null;
            /** Track Keyword Rank */
            track_keyword_rank?: boolean | null;
        };
        /**
         * PromptResult
         * @description Latest state of one prompt across the project's platforms.
         */
        PromptResult: {
            /** Due On */
            due_on?: components["schemas"]["Engine"][];
            /** Effective Engines */
            effective_engines: components["schemas"]["Engine"][];
            /** Effective Interval */
            effective_interval: string;
            organic_keyword?: components["schemas"]["OrganicRankSnapshot"] | null;
            organic_prompt?: components["schemas"]["OrganicRankSnapshot"] | null;
            prompt: components["schemas"]["TrackedPrompt"];
            /** Snapshots */
            snapshots?: {
                [key: string]: components["schemas"]["CitationSnapshot"] | null;
            };
        };
        /**
         * RankQueryKind
         * @description Which query string an organic ranking was measured for.
         * @enum {string}
         */
        RankQueryKind: "PROMPT" | "KEYWORD";
        /**
         * RejectedPage
         * @description A client page an engine consulted and did not cite.
         */
        RejectedPage: {
            engine: components["schemas"]["Engine"];
            /** Queries */
            queries?: string[];
            /** Samples */
            samples: number;
            /** Url */
            url: string;
        };
        /**
         * RunCost
         * @description Spend attributed to one tracker run.
         */
        RunCost: {
            /** Actual Usd */
            actual_usd: number;
            /** By Vendor */
            by_vendor?: {
                [key: string]: number;
            };
            /** Calls */
            calls: number;
            /** Estimated Usd */
            estimated_usd: number;
            /** Run Id */
            run_id: string;
        };
        /**
         * RunJob
         * @description A run submitted from the UI or the poller, executed in the background.
         */
        RunJob: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            outcome?: components["schemas"]["RunOutcome"] | null;
            /**
             * Position
             * @description Jobs ahead in the queue (0 = next).
             * @default 0
             */
            position: number;
            progress?: components["schemas"]["RunProgress"];
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string;
            request: components["schemas"]["RunRequest"];
            /** Started At */
            started_at?: string | null;
            /** @default queued */
            state: components["schemas"]["JobState"];
        };
        /**
         * RunOutcome
         * @description What a project run did.
         */
        RunOutcome: {
            /** Batches */
            batches: number;
            /**
             * Consolidation Id
             * @description Set when this crawl completed a consolidation window.
             */
            consolidation_id?: string | null;
            /** Project Id */
            project_id: string;
            /**
             * Project Run Id
             * @description Crawl record id, if recorded.
             */
            project_run_id?: string | null;
            /** Prompts Run */
            prompts_run: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Run Ids */
            run_ids?: string[];
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Statuses */
            statuses?: string[];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * RunProgress
         * @description Live progress of one project run, folded across its batches.
         *
         *     `checks` are prompt x platform audits; `percent` is checks_done / checks_total.
         */
        RunProgress: {
            /**
             * Batches Done
             * @default 0
             */
            batches_done: number;
            /**
             * Batches Total
             * @default 0
             */
            batches_total: number;
            /**
             * Checks Done
             * @default 0
             */
            checks_done: number;
            /**
             * Checks Total
             * @default 0
             */
            checks_total: number;
            /**
             * Engine Calls
             * @default 0
             */
            engine_calls: number;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Percent
             * @default 0
             */
            percent: number;
            /**
             * Phase
             * @description queued|planning|harvest|audit|…|done
             * @default queued
             */
            phase: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /**
         * RunRequest
         * @description Body for `POST /api/projects/{id}/run`.
         */
        RunRequest: {
            /**
             * Engines
             * @description Restrict to these platforms.
             */
            engines?: components["schemas"]["Engine"][] | null;
            /**
             * Force
             * @description Run even if nothing is due.
             * @default false
             */
            force: boolean;
            /**
             * Prompt Ids
             * @description Restrict to these prompts.
             */
            prompt_ids?: string[];
        };
        /**
         * RunRow
         * @description One row of a project's runs table.
         */
        RunRow: {
            /** Engine Calls */
            engine_calls: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /** Failed Engine Calls */
            failed_engine_calls: number;
            /** Finished At */
            finished_at: string;
            /** Prompts Selected */
            prompts_selected: number;
            /** Report Path */
            report_path: string | null;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at: string;
        };
        /**
         * SourceSnippet
         * @description The passage of a source the engine surfaced, with its date when known.
         */
        SourceSnippet: {
            /**
             * Date
             * @description Vendor-reported publish/update date.
             */
            date?: string | null;
            /**
             * Snippet
             * @default
             */
            snippet: string;
            /** Title */
            title?: string | null;
            /** Url */
            url: string;
        };
        /**
         * TrackedPrompt
         * @description A stored prompt.
         */
        TrackedPrompt: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Engines
             * @description Overrides the project platforms.
             */
            engines?: components["schemas"]["Engine"][] | null;
            /** Id */
            id: string;
            /**
             * Important
             * @description Starred; surfaces first in the UI.
             * @default false
             */
            important: boolean;
            /**
             * Interval
             * @description Overrides the project interval.
             */
            interval?: string | null;
            /** Keyword */
            keyword?: string | null;
            /** Project Id */
            project_id: string;
            /**
             * Prompt Id
             * @description Stable hash shared with the time-series store.
             */
            prompt_id: string;
            /** Prompt Text */
            prompt_text: string;
            /** Samples Per Engine */
            samples_per_engine?: number | null;
            /** Subtopic */
            subtopic?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * TrackedPromptCreate
         * @description Body for adding a prompt.
         */
        TrackedPromptCreate: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Engines
             * @description Overrides the project platforms.
             */
            engines?: components["schemas"]["Engine"][] | null;
            /**
             * Important
             * @description Starred; surfaces first in the UI.
             * @default false
             */
            important: boolean;
            /**
             * Interval
             * @description Overrides the project interval.
             */
            interval?: string | null;
            /** Keyword */
            keyword?: string | null;
            /** Prompt Text */
            prompt_text: string;
            /** Samples Per Engine */
            samples_per_engine?: number | null;
            /** Subtopic */
            subtopic?: string | null;
        };
        /**
         * TrackedPromptUpdate
         * @description Partial update; only supplied fields change. Overrides can be cleared as a whole.
         */
        TrackedPromptUpdate: {
            /**
             * Clear Overrides
             * @description Reset interval/engines/samples overrides to the project's.
             * @default false
             */
            clear_overrides: boolean;
            /** Enabled */
            enabled?: boolean | null;
            /** Engines */
            engines?: components["schemas"]["Engine"][] | null;
            /** Important */
            important?: boolean | null;
            /** Interval */
            interval?: string | null;
            /** Keyword */
            keyword?: string | null;
            /** Prompt Text */
            prompt_text?: string | null;
            /** Samples Per Engine */
            samples_per_engine?: number | null;
            /** Subtopic */
            subtopic?: string | null;
        };
        /**
         * TrustShare
         * @description What kind of sites an engine cites for this project.
         */
        TrustShare: {
            /** Citations */
            citations: number;
            /** Domain Class */
            domain_class: string;
            engine: components["schemas"]["Engine"];
            /** Share */
            share: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VendorCost
         * @description Volume and spend for one vendor.
         */
        VendorCost: {
            /**
             * Actual Usd
             * @description Vendor-reported, else modelled, else estimate.
             */
            actual_usd: number;
            /** Calls */
            calls: number;
            /** Calls With Modelled Cost */
            calls_with_modelled_cost: number;
            /** Calls With Vendor Cost */
            calls_with_vendor_cost: number;
            /** Errors */
            errors: number;
            /** Estimated Usd */
            estimated_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Latency P50 Ms */
            latency_p50_ms: number;
            /** Latency P95 Ms */
            latency_p95_ms: number;
            /** Mean Actual Per Ok Call */
            mean_actual_per_ok_call: number;
            /** Mean Estimated Per Call */
            mean_estimated_per_call: number;
            /** Modelled Usd */
            modelled_usd: number;
            /** Ok */
            ok: number;
            /** Output Tokens */
            output_tokens: number;
            /** Refused */
            refused: number;
            /** Search Calls */
            search_calls: number;
            /** Units */
            units: number;
            /** Vendor */
            vendor: string;
            /** Vendor Reported Usd */
            vendor_reported_usd: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    costs_api_costs_get: {
        parameters: {
            query?: {
                days?: number | null;
                exclude_source?: string | null;
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    all_jobs_api_jobs_get: {
        parameters: {
            query?: {
                active?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_api_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_action_api_projects__project_id__actions__action_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consolidate_api_projects__project_id__consolidate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConsolidateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consolidation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crawls_api_projects__project_id__crawls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRunRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_projects__project_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insights_api_projects__project_id__insights_get: {
        parameters: {
            query?: {
                consolidation_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_jobs_api_projects__project_id__jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    positions_api_projects__project_id__positions_get: {
        parameters: {
            query?: {
                consolidation_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prompts_api_projects__project_id__prompts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedPrompt"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_prompt_api_projects__project_id__prompts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackedPromptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedPrompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_prompt_api_projects__project_id__prompts__tracked_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                tracked_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackedPromptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedPrompt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_prompt_api_projects__project_id__prompts__tracked_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                tracked_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_prompts_api_projects__project_id__prompts_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackedPrompt"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_api_projects__project_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_projects__project_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_api_projects__project_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    samples_api_projects__project_id__samples_get: {
        parameters: {
            query: {
                engine?: components["schemas"]["Engine"] | null;
                prompt_id: string;
                run_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerSample"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
