// Regenerates src/api/schema.d.ts from the control plane's OpenAPI document.
// Source order: OPENAPI_URL env, the running server, then the checked-in
// snapshot (src/api/openapi.json) so CI can run without a server.
import { readFile, writeFile } from "node:fs/promises";
import openapiTS, { astToString } from "openapi-typescript";

const url = process.env.OPENAPI_URL ?? "http://127.0.0.1:8787/openapi.json";
const snapshot = new URL("../src/api/openapi.json", import.meta.url);

async function load() {
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
    const text = await res.text();
    await writeFile(snapshot, text);
    console.log(`OpenAPI fetched from ${url} and snapshot updated.`);
    return JSON.parse(text);
  } catch (err) {
    console.log(`Server unavailable (${err.message}); using the snapshot.`);
    return JSON.parse(await readFile(snapshot, "utf8"));
  }
}

const doc = await load();
const ast = await openapiTS(doc, { alphabetize: true });
const header = "// GENERATED by scripts/gen-types.mjs from the control plane OpenAPI. Do not edit.\n";
await writeFile(new URL("../src/api/schema.d.ts", import.meta.url), header + astToString(ast));
console.log("Wrote src/api/schema.d.ts");
